### ISSUE TITLE
level-3.txt 中「峏」应为「峘」。

### ISSUE THREAD

**Issue by rodrigo-morales-1** [shengdoushi/common-standard-chinese-characters-table#1]
I downloaded the document 《通用规范汉字表》 from this URL: https://www.gov.cn/gzdt/att/att/site1/20130819/tygfhzb.pdf

I have noticed that the character 6836 is missing in the file  `level-3.txt`. The screenshot below shows the range 6833-6839:

![image](https://github.com/user-attachments/assets/90ffe17e-ce83-4e22-9f19-8fca2d15a9b3)

The following code block shows the characters from the range 6833-6839 in the file `level-3.txt`. I think 峘 (U+5CD8) should be written instead of 峏 (U+5CCF).

https://github.com/shengdoushi/common-standard-chinese-characters-table/blob/9c450ebdc4680820010745a6f1078562127739bf/level-3.txt#L333-L339

Here are two additional sources where the character 峘 (U+5CD8) is used and the character 峏 (U+5CCF) is not used:

* [github.com - rime-aca/character_set/通用規範漢字表.txt](https://github.com/rime-aca/character_set/blob/05db9d8194448d0ed2c916a89c62a7a0bda60c30/%E9%80%9A%E7%94%A8%E8%A6%8F%E7%AF%84%E6%BC%A2%E5%AD%97%E8%A1%A8.txt#L6839)
* [zh.wikisource.org - 通用规范汉字表](https://zh.wikisource.org/w/index.php?title=通用规范汉字表&oldid=2454711#三级字表)

**Comment by shengdoushi** [comment]
已校正
